/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.2 and DSP System Toolbox 24.2.
 * Generated on: 15-Jul-2025 10:33:42
 */

/*
 * 离散时间 FIR 滤波器(实数)
 * ----------------
 * 滤波器结构    : 直接型 FIR
 * 滤波器长度    : 51
 * 稳定       : 是
 * 线性相位     : 是 (Type 1)
 * 算术       : fixed
 * 分子       : s16,16 -> [-5.000000e-01 5.000000e-01)
 * 输入       : s12,0 -> [-2048 2048)
 * 滤波器内部选项  : Full Precision
 *   输出     : s30,16 -> [-8192 8192)  (auto determined)
 *   乘积     : s27,16 -> [-1024 1024)  (auto determined)
 *   累加器    : s30,16 -> [-8192 8192)  (auto determined)
 *   取整模式   : No rounding
 *   溢出模式   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\matlab\software\extern\include\tmwtypes.h 
 */
const int BL = 51;
const int16_T B[51] = {
      -60,   -178,   -163,    240,    895,   1137,    502,   -430,   -504,
      400,    909,     23,  -1108,   -584,   1143,   1360,   -806,  -2244,
      -68,   3132,   1793,  -3891,  -5394,   4403,  20317,  28184,  20317,
     4403,  -5394,  -3891,   1793,   3132,    -68,  -2244,   -806,   1360,
     1143,   -584,  -1108,     23,    909,    400,   -504,   -430,    502,
     1137,    895,    240,   -163,   -178,    -60
};
